# Generated by Django 4.0.4 on 2022-04-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leads',
            new_name='Lead',
        ),
    ]
